engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - "**.js"
languages:
  JavaScript: true
exclude_paths:
  - server/test/
