engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
    - server/**
    - server/**/*.js
languages:
  JavaScript: true
exclude_paths:
