engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      angular/controller-as:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "public/js/*"
languages:
  JavaScript: true
exclude_paths:
- .travis.yml
- .eslintrc
- server.js
- gulpfile.js
