sudo: required
dist: trusty
language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - psql -c 'create database jedDoc_test;' -U postgres
script: npm test
# after_script:
#   - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success: npm run coverage
