sudo: required
dist: trusty
language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - psql -c 'create database postgres;' -U postgres
script: npm test
addons:
  postgresql: "9.6"
# after_script:
#   - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
after_success: npm run coverage
